In [13]:
import numpy as np

In [14]:
mylist=[1,2,3,4]

In [ ]:
myarr1=np.array(mylist)
print(myarr1)

[1 2 3 4]


In [17]:
myarr1.shape

(4,)

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
mylist2=[1,2,3]
mylist3=[4,5,6]
myarr2=mylist2,mylist3
np.array(myarr2)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
mylist2=[1,2,3]
mylist3=[4,5,6]
mylist4=[7,8,9]
myarr2=mylist2,mylist3,mylist4
np.array(myarr2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])